dist: bionic
language: node_js

node_js:
  - '12'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)-dev$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - echo $(pwd)
  - npm i
  - cp .env.example .env
  # Build docker image
  - docker build -t platform-test-suite:local .
  # Install MN Bootstrap
  - chmod +x ./scripts/get-gh-release-link
  - curl -L $(./scripts/get-gh-release-link dashevo/mn-bootstrap) > mn-bootstrap.tar.gz
  - mkdir ~/mn-bootstrap && tar -C ~/mn-bootstrap -xvf mn-bootstrap.tar.gz
  - pushd ~/mn-bootstrap/$(ls ~/mn-bootstrap) && npm install && npm link

before_script: >
  source scripts/register-mn.sh &&
  mn start local -p $OPERATOR_BLS_KEY 127.0.0.1 20001

script: >
  popd &&
  npm run check-package &&
  npm run lint &&
  docker run platform-test-suite:local 127.0.0.1 -k=$PRIVATE_KEY -n=regtest

after_script:
  - mn stop local

deploy:
  provider: script
  script: bash scripts/travis-deploy.sh
  on:
    tags: true
    repo: dashevo/platform-test-suite
