dist: bionic
language: node_js

node_js:
  - '12'

branches:
  only:
    - master

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - mkdir -p ~/.local/bin
  - curl -fsSL -o ~/.local/bin/dash-network https://raw.github.com/dashpay/dash-network-deploy/master/bin/dash-network && chmod +x ~/.local/bin/dash-network
  - git clone https://$NETWORK_CONFIGS_GITHUB_USERNAME:$NETWORK_CONFIGS_GITHUB_TOKEN@github.com/nmarley/dash-network-configs ~/dash-network-configs
  - cp ~/dash-network-configs/$NETWORK_CONFIGS_PATH/.env.example ~/dash-network-configs/$NETWORK_CONFIGS_PATH/.env

install:
  - npm ci

script:
  - cd ~/dash-network-configs/$NETWORK_CONFIGS_PATH
  - ~/.local/bin/dash-network test $DEVNET
  - cd $TRAVIS_BUILD_DIR
  - npm run test

notifications:
  email:
    - konstantin.shuplenkov@dash.org
    - ivan.shumkov@dash.org
    - anton.suprunchuk@dash.org
    - djavid@dash.org
  slack:
    rooms:
      - secure: n16Ae3rLliwoJdaCGkVzlzgips7w1+bKYA07spnj9NU4IoI1kfVBhLkQbNkAnwshYuYAjMmMxG+sQr0oNSLLIA3EFL8Eg91PuGA4nl7g0Hp+KN6Ow2/xmPOQChr0VfI+wgPr5koSXzzboR2EV4VsFf7WGDFBmvbrGLIWHqyTTn4oJmi3YFT47A1lm7qcRsIZ+S4q4OQUcRTRorHQcIHfIpB+DfuSGonw+VGZ1xcuwfJDT86flgU2t7zyxD41F+Z/WUNS9IdxSGCBJOtD2WSVj0JXxyEPoPZN1GSqEoflHvqNbqIOvCAFAb0SftmS9obbEF9rTFjFAOwasS1LXDl5N9o9ifM5lvoCQET6ddphIGbdqzwCJc453OcorJr1QNtxTLM9GPPeeCkkgTipjLv3iaq9Ayq09kG6DZG6sffsCJdYFGZqQrWVQEYBGbLXEhL1kh/x4JoJFRPYMnRE4TW3Crp2pW4cO24ofZvRwtZlLkKu/+lVMA3Io4NTonxg4Q2lQ5nJpTJy+DO4tIQ34tviFjbC4207iDEpY4cRaObTqSTPLN11JQqKo+/Dwt1r/EiQH+fYM0n/ZmCE4VDRr9TBnbXuOQyGP/KZ28VbZrnltScWuABFdWNqmZFGKbZTNG1o+Q0PnhHbuwPAGF17P/5YcFD4nzdAuq3/x3q28PULxmw=
    on_success: never
    on_failure: always


