dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '12'

branches:
  only:
    - master

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - mkdir -p ~/.local/bin
  - curl -fsSL -o ~/.local/bin/dash-network https://raw.github.com/dashpay/dash-network-deploy/master/bin/dash-network && chmod +x ~/.local/bin/dash-network
  - git clone https://$NETWORK_CONFIGS_GITHUB_USERNAME:$NETWORK_CONFIGS_GITHUB_TOKEN@github.com/nmarley/dash-network-configs ~/dash-network-configs
  - cp ~/dash-network-configs/$NETWORK/.env.example ~/dash-network-configs/$NETWORK/.env

install:
  - npm ci
  - cp .env.example .env

script:
  - pushd ~/dash-network-configs/$NETWORK
  - ~/.local/bin/dash-network test $NETWORK
  - popd
  - npm run test
