dist: bionic
language: node_js

node_js:
  - '12'

branches:
  only:
    - master

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - mkdir -p ~/.local/bin
  - curl -fsSL -o ~/.local/bin/dash-network https://raw.github.com/dashpay/dash-network-deploy/master/bin/dash-network && chmod +x ~/.local/bin/dash-network
  - git clone https://$NETWORK_CONFIGS_GITHUB_USERNAME:$NETWORK_CONFIGS_GITHUB_TOKEN@github.com/nmarley/dash-network-configs ~/dash-network-configs
  - cp ~/dash-network-configs/$NETWORK_CONFIGS_PATH/.env.example ~/dash-network-configs/$NETWORK_CONFIGS_PATH/.env

install:
  - npm ci

script:
  - cd ~/dash-network-configs/$NETWORK_CONFIGS_PATH
  - ~/.local/bin/dash-network test $DEVNET
  - cd $TRAVIS_BUILD_DIR
  - npm run test

notifications:
  email:
    - konstantin.shuplenkov@dash.org
    - ivan.shumkov@dash.org
    - anton.suprunchuk@dash.org
    - djavid@dash.org
  slack:
    rooms:
      - dashpay:zp7QAibBWt0ALllpLqhb51q0
    on_success: never
    on_failure: always


